CREATE DATABASE JOB_TRACKER;
-- CREATE USER
CREATE USER 'sysadmin'@'localhost' IDENTIFIED BY '******';
-- PRIVILÉGIOS DO USUÁRIO
GRANT ALL PRIVILEGES ON JOB_TRACKER.* TO 'sysadmin'@'localhost';

SHOW DATABASES;
USE JOB_TRACKER;

-- CREATE TABLES AND CONSTRAINTS
CREATE TABLE ENTERPRISE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE JOB(
ID INT PRIMARY KEY AUTO_INCREMENT,
POSITION VARCHAR(50) NOT NULL,
DESCRIPTION TEXT NOT NULL,
DATE_OPENING DATE NOT NULL,
DATE_CLOSING DATE,
ENTERPRISE_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(ENTERPRISE_ID) REFERENCES ENTERPRISE(ID)
);

CREATE TABLE TYPE_RECRUITER(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RECRUITER(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
TYPE_RECRUITER_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(TYPE_RECRUITER_ID) REFERENCES TYPE_RECRUITER(ID)
);

CREATE TABLE JOB_RECRUITER(
ID INT PRIMARY KEY AUTO_INCREMENT,
JOB_ID INT NOT NULL,
RECRUITER_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(JOB_ID) REFERENCES JOB(ID),
FOREIGN KEY(RECRUITER_ID) REFERENCES RECRUITER(ID)
);

CREATE TABLE APPLICATION_STATUS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME_STATUS VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE STATUS_INTERVIEW(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME_STATUS VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CANDIDATE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
PHONE VARCHAR(25) NOT NULL,
EMAIL VARCHAR(150) NOT NULL UNIQUE,
ADDRESS VARCHAR(255),
LINKEDIN VARCHAR(255),
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE JOB_APPLICATION(
ID INT PRIMARY KEY AUTO_INCREMENT,
JOB_ID INT NOT NULL,
CANDIDATE_ID INT NOT NULL,
APPLICATION_STATUS_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(JOB_ID) REFERENCES JOB(ID),
FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(ID),
FOREIGN KEY(APPLICATION_STATUS_ID) REFERENCES APPLICATION_STATUS(ID)
);

CREATE TABLE INTERVIEW(
ID INT PRIMARY KEY AUTO_INCREMENT,
JOB_APPLICATION_ID INT NOT NULL,
INTERVIEW_DATE DATETIME NOT NULL,
STATUS_INTERVIEW_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(JOB_APPLICATION_ID) REFERENCES JOB_APPLICATION(ID),
FOREIGN KEY(STATUS_INTERVIEW_ID) REFERENCES	STATUS_INTERVIEW(ID)
);

CREATE TABLE INTERVIEW_RECRUITER(
ID INT PRIMARY KEY AUTO_INCREMENT,
RECRUITER_ID INT NOT NULL,
INTERVIEW_ID INT NOT NULL,
OBSERVER TEXT,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY (RECRUITER_ID) REFERENCES RECRUITER(ID),
FOREIGN KEY (INTERVIEW_ID) REFERENCES INTERVIEW(ID)
);

CREATE TABLE TRAINING_TYPE(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CANDIDATE_TRAINING(
ID INT PRIMARY KEY AUTO_INCREMENT,
CANDIDATE_ID INT NOT NULL,
DESCRIPTION VARCHAR(150) NOT NULL,
TRAINING_TYPE_ID INT NOT NULL,
DATE_START DATE NOT NULL,
DATE_END DATE,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(ID),
FOREIGN KEY(TRAINING_TYPE_ID) REFERENCES TRAINING_TYPE(ID)
);

CREATE TABLE CANDIDATE_EXPERIENCE(
ID INT PRIMARY KEY AUTO_INCREMENT,
CANDIDATE_ID INT NOT NULL,
ENTERPRISE VARCHAR(50) NOT NULL,
POSITION VARCHAR(50),
DATE_START DATE NOT NULL,
DATE_END DATE,
DESCRIPTION TEXT,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(ID)
);

CREATE TABLE LANGUAGE(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE LEVEL_LANGUAGE(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION CHAR(2) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CANDIDATE_LANGUAGE(
ID INT PRIMARY KEY AUTO_INCREMENT,
LANGUAGE_ID INT NOT NULL,
LEVEL_LANGUAGE_ID INT NOT NULL,
CANDIDATE_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(ID),
FOREIGN KEY(LEVEL_LANGUAGE_ID) REFERENCES LEVEL_LANGUAGE(ID),
FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(ID)
);

CREATE TABLE SKILL(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(20) NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CANDIDATE_SKILL(
ID INT PRIMARY KEY AUTO_INCREMENT,
SKILL_ID INT NOT NULL,
CANDIDATE_ID INT NOT NULL,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY(SKILL_ID) REFERENCES SKILL(ID),
FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(ID)
);

-- ADICIONANDO CONSTRAINTS
ALTER TABLE JOB_RECRUITER
ADD CONSTRAINT UK_JOB_RECRUITER
UNIQUE (JOB_ID, RECRUITER_ID);

ALTER TABLE CANDIDATE_LANGUAGE
ADD CONSTRAINT UK_CANDIDATE_LANGUAGE
UNIQUE (CANDIDATE_ID, LANGUAGE_ID);

ALTER TABLE CANDIDATE_SKILL
ADD CONSTRAINT UK_CANDIDATE_SKILL
UNIQUE (CANDIDATE_ID, SKILL_ID);


--Permissão para criar objetos
GRANT CREATE ROUTINE ON job_tracker.* TO 'sysadmin'@'localhost';
GRANT CREATE VIEW ON job_tracker.* TO 'sysadmin'@'localhost';
GRANT TRIGGER ON job_tracker.* TO 'sysadmin'@'localhost';
GRANT CREATE ROUTINE, ALTER ROUTINE, CREATE VIEW, TRIGGER ON job_tracker.* TO 'sysadmin'@'localhost';
SET GLOBAL log_bin_trust_function_creators = 1;


-- Function like INITCAP (Oracle)
DELIMITER $$

CREATE FUNCTION CAPFIRST(texto VARCHAR(255)) 
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
    DECLARE passo INT DEFAULT 1;
    DECLARE caractere CHAR(1);
    DECLARE resultado VARCHAR(255) DEFAULT '';
    DECLARE proxima_maiuscula BOOLEAN DEFAULT TRUE;

    WHILE passo <= LENGTH(texto) DO
        SET caractere = SUBSTRING(texto, passo, 1);

        IF caractere = ' ' THEN
            SET proxima_maiuscula = TRUE;
            SET resultado = CONCAT(resultado, ' ');
        ELSE
            IF proxima_maiuscula THEN
                SET resultado = CONCAT(resultado, UPPER(caractere));
                SET proxima_maiuscula = FALSE;
            ELSE
                SET resultado = CONCAT(resultado, LOWER(caractere));
            END IF;
        END IF;

        SET passo = passo + 1;
    END WHILE;

    RETURN resultado;
END$$

DELIMITER ;


-- Function country name
DELIMITER $$

CREATE FUNCTION COUNTRY_NAME(p_country_id CHAR(3))
RETURNS VARCHAR(30)
DETERMINISTIC
NO SQL
BEGIN
    DECLARE v_country_name VARCHAR(30);
    
    SELECT  name
    INTO    v_country_name
    FROM    country
    WHERE   id = p_country_id;
    
    RETURN v_country_name;
END$$

DELIMITER ;


-- Incrementando campos na tabela candidate
ALTER TABLE CANDIDATE
ADD COLUMN CITY VARCHAR(30) AFTER ADDRESS,
ADD COLUMN COUNTRY CHAR(3) AFTER CITY,
ADD CONSTRAINT FK_CANDIDATE_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID);


ALTER TABLE CANDIDATE_EXPERIENCE
RENAME COLUMN DATE_START TO START_DATE,
RENAME COLUMN DATE_END TO END_DATE;


CREATE TABLE TYPE_LOCATION (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL
);

INSERT INTO TYPE_LOCATION (NAME) 
VALUES('On-site'),('Remote'),('Hybrid');

ALTER TABLE CANDIDATE_EXPERIENCE
ADD COLUMN COUNTRY_ID CHAR(3) AFTER POSITION,
ADD COLUMN TYPE_LOCATION_ID INT,
ADD CONSTRAINT FK_EXPERIENCE_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
ADD CONSTRAINT FK_EXPERIENCE_TYPE_LOCATION FOREIGN KEY (TYPE_LOCATION_ID) REFERENCES TYPE_LOCATION (ID);


DELIMITER $$

CREATE FUNCTION TYPE_LOCATION_NAME(type_location_id CHAR(3)) 
RETURNS VARCHAR(20)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_name VARCHAR(20);

    -- Busca o nome baseado no ID passado por parâmetro
    SELECT name 
    INTO v_name
    FROM TYPE_LOCATION
    WHERE id = type_location_id
    LIMIT 1; -- Garante que retorne apenas uma linha

    -- Retorna o nome encontrado (ou NULL se não encontrar nada)
    RETURN v_name;
END$$

DELIMITER ;